### ISSUE TITLE
Reconcile Cash

### ISSUE THREAD

**Issue by liasyifa** [ljcom/operahouse#101]
1. Status transaksi belum sesuai :

![image](https://user-images.githubusercontent.com/28723751/34807291-85fd3b6a-f6ba-11e7-8068-fdf1cdccd72b.png)

2. Create New --> Klik Save muncul error seperti dibawah ini :

![image](https://user-images.githubusercontent.com/28723751/34807349-e811212c-f6ba-11e7-9ce4-1ca23681fd79.png)

**Comment by ljcom** [comment]
Harusnya ini apa? Transaksi?




<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

**Comment by liasyifa** [comment]
Seharus nya transaksi Pak

**Comment by liasyifa** [comment]
Tampilan terupdate klik Reconcile Cash , blank seperti dibawah ini :

![image](https://user-images.githubusercontent.com/28723751/34811241-7f533ec8-f6d2-11e7-85eb-f26f7617dc15.png)

**Comment by liasyifa** [comment]
Done
