### ISSUE TITLE
Master Brand

### ISSUE THREAD

**Issue by liasyifa** [ljcom/operahouse#115]
Create New --> Klik Save muncul error seperti dibawah ini :

![image](https://user-images.githubusercontent.com/28723751/34812833-07901ff2-f6da-11e7-9bc7-19814741454c.png)

**Comment by rizkasep** [comment]
Sudah di setting bisa masuk dan buat new document, hapus detail sudah bisa tapi hapus headernya keterangan success tidak pindah ke status delete masih tetap di active.
