### ISSUE TITLE
Master Bank

### ISSUE THREAD

**Issue by liasyifa** [ljcom/operahouse#116]
Create New --> Klik Save muncul error seperti dibawah ini :

![image](https://user-images.githubusercontent.com/28723751/34812914-63511c9c-f6da-11e7-85a8-d90d38f23172.png)

**Comment by rizkasep** [comment]
Sudah di setting bisa masuk dan save transaksi header serta detailnya. namu ketika di hapus detailnya hilang di refresh muncul kembali, untuk header di hapus tidak hilang.
