### ISSUE TITLE
MODL, UGRP & USER (Create New Blank)

### ISSUE THREAD

**Issue by liasyifa** [ljcom/operahouse#18]
MODL, UGRP & USER : Create New, form belum muncul seperti gambar dibawah ini  :

![image](https://user-images.githubusercontent.com/28723751/26916828-fb2fcfa2-4c55-11e7-869e-8ea60d0cb484.png)

**Comment by ljcom** [comment]
kesenggol linggar pas buat zoning. cek lagi!

**Comment by liasyifa** [comment]
Done
