### ISSUE TITLE
HRRR, HRCH, TaVEND, TaVENA, TaPROD, TaDEDU, MaITPC ??

### ISSUE THREAD

**Issue by liasyifa** [ljcom/operahouse#21]
Klik HRRR, HRCH, New Vendor (TaVEND), Vendor Change Request (TaVENA), ILF (TaPROD), Deduction (TaDEDU), Master IT PC Inventory (MaITPC) masuk kehalaman ini :

![image](https://user-images.githubusercontent.com/28723751/26921747-29030884-4c67-11e7-8527-4dbddc23b7bb.png)

**Comment by ljcom** [comment]
HRRR? kenapa bukan taHRRR?
![image](https://user-images.githubusercontent.com/1333324/26959450-6eb29640-4cfa-11e7-8d36-eae01ee90a56.png)

HRCH kenapa bukan taHRCH?

TaVEND (bisa masuk sih), 
![image](https://user-images.githubusercontent.com/1333324/26959470-8f0930d4-4cfa-11e7-8fc5-6427d75483d3.png)

TaVENA fixed!

TaPROD fixed! 

TaDEDU fixed! 

MaITPC fixed!

**Comment by liasyifa** [comment]
Done
