### ISSUE TITLE
Master Periode

### ISSUE THREAD

**Issue by liasyifa** [ljcom/operahouse#97]
1. Create New --> Klik Save muncul error seperti dibawah ini :
![image](https://user-images.githubusercontent.com/28723751/34806744-7510a934-f6b7-11e7-9dde-387b444d07ee.png)

2. Field yanga ada pada Detail blm sesuai

**Comment by ljcom** [comment]
done. Please check.



<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

**Comment by liasyifa** [comment]
Terupdate ketika Create New --> Klik Save muncul error seperti dibawah ini :

![image](https://user-images.githubusercontent.com/28723751/34811405-4c839410-f6d3-11e7-9c78-59e90df0fbf1.png)
